FROM python:3.11.4-slim-buster 

WORKDIR /home/app/web

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev musl-dev

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN mkdir -p /home/app/web/server/staticfiles
RUN mkdir -p /home/app/web/server/mediafiles


RUN adduser --disabled-password --no-create-home app
USER app
RUN cd /home/app/web/