from django.urls import path
from .views import *
app_name = "main"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login", LoginView.as_view(), name="login"),
    path("signup", SignupView.as_view(), name="signup"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("setup", setup_view, name="setup"),
    path("setup/movies", setup_movies_view, name="setup_movies"),
    path("show/<str:show_id>", ShowView.as_view(), name="show"),
    path("book/", BookView.as_view(), name="book"),
    path("ticket/<uuid:ticket_id>/cancel/",
         CancelTicketView.as_view(), name="cancel_ticket"),
    path("confirm/<uuid:transaction_id>/",
         ConfirmTransactionView.as_view(), name="confirm_transaction"),
    path("ticket/<uuid:ticket_id>/food/",
         FoodOrderView.as_view(), name="order_food"),
    path("wallet", wallet, name="wallet"),
    path("withdraw", withdraw, name="withdraw"),
    path("add", add, name="add"),
    path("404", not_found_404, name="404"),
    path("account", AccountView.as_view(), name="account"),
    path("tickets", TicketView.as_view(), name="tickets"),
    path("movies", movies, name="movies"),
    path("shows/<uuid:movie_id>", shows, name="shows"),
    path("ticket/<uuid:ticket_id>", ticket, name="ticket"),
    path("transaction/<uuid:transaction_id>", transaction, name="transaction"),
    path("transactions", transactions, name="transactions"),
    path("password_change", PasswordChangeView.as_view(), name="password_change"),
    path("account_edit", AccountEditView.as_view(), name="account_edit"),
    path("search/", search_shows, name="search"),
    path("theatres", theatres, name="theatres"),
    path("theatre/<uuid:theatre_id>", theatre, name="theatre"),

]

th_admin_urls = [
    path("th_admin", AdminLoginView.as_view(), name="th_admin"),
    path("th_admin/home", admin_home, name="th_admin_home"),
    path("th_admin/logout", admin_logout, name="th_admin_logout"),
    path("th_admin/food", AdminFoodView.as_view(), name="th_admin_food"),
    path("th_admin/food/edit/<uuid:food_id>",
         EditFoodView.as_view(), name="th_admin_edit_food"),
    path("th_admin/food/add/",
         AddFoodView.as_view(), name="th_admin_add_food"),
    path("th_admin/food/delete/<uuid:food_id>",
         delete_food_item, name="th_admin_delete_food"),
    path("th_admin/show", AdminShowView.as_view(), name="th_admin_show"),
    path("th_admin/show/edit/<uuid:show_id>",
         EditShowView.as_view(), name="th_admin_edit_show"),
    path("th_admin/show/add/",
         AddShowView.as_view(), name="th_admin_add_show"),
    path("th_admin/show/delete/<uuid:show_id>",
         delete_show_view, name="th_admin_delete_show"),
    path("th_admin/bookings", admin_booking_view, name="th_admin_bookings"),
    path("th_admin/register", register_th_admin, name="register_th_admin"),
    path("th_admin/screens", screen_view, name="th_admin_screen"),
    path("th_admin/screen/add", AddScreenView.as_view(),
         name="th_admin_add_screen"),
    path("th_admin/screen/edit/<uuid:screen_id>",
         EditScreenView.as_view(), name="th_admin_edit_screen"),
    path("th_admin/screen/delete/<uuid:screen_id>",
         delete_screen_view, name="th_admin_delete_screen"),
    path("th_admin/ticket_details/<uuid:ticket_id>", admin_ticket_details,
         name="th_admin_ticket_details"),
    path("th_admin/tickets/cancel", admin_ticket_cancel,
         name="th_admin_cancel_ticket"),
    path("th_admin/tickets/used", admin_ticket_used, name="th_admin_ticket_used"),
]

urlpatterns.extend(th_admin_urls)
