# Generated by Django 5.1 on 2024-10-31 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_tickets_alter_user_transaction_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING')], max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('otp', models.IntegerField(default=304912, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('movie_date', models.DateTimeField()),
                ('price', models.IntegerField(default=100)),
                ('used', models.BooleanField(default=False)),
                ('food_orders', models.JSONField(default=None, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transaction')),
            ],
        ),
    ]
