# Generated by Django 5.1 on 2024-11-01 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_food_movie_theatre_remove_ticket_movie_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='theatre_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.theatreadmin'),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=397741, editable=False),
        ),
    ]
