# Generated by Django 5.1 on 2024-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_show_available_seats_alter_transaction_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=166775, editable=False),
        ),
    ]
