# Generated by Django 5.1 on 2024-11-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_transaction_exceuted_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=369929, editable=False),
        ),
    ]
