# Generated by Django 5.1.3 on 2024-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_food_id_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_id',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=207620, editable=False),
        ),
    ]
