# Generated by Django 5.1.3 on 2024-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='food_orders',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=309129, editable=False),
        ),
    ]
