# Generated by Django 5.1.3 on 2024-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_ticket_food_orders_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='food_order_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=341176, editable=False),
        ),
    ]
