# Generated by Django 5.1.3 on 2024-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_screen_type_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('snacks', 'snacks'), ('beverages', 'beverages'), ('combos', 'combos')], default='snacks', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=430792, editable=False),
        ),
    ]
