# Generated by Django 5.1 on 2024-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tickets',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='transaction_history',
            field=models.JSONField(default=None, null=True),
        ),
    ]
