# Generated by Django 5.1 on 2024-11-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_theatre_uuid_alter_movie_id_alter_theatre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=304111, editable=False),
        ),
    ]
