# Generated by Django 5.1 on 2024-11-01 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_transaction_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='theatre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=289988, editable=False),
        ),
    ]
