# Generated by Django 5.1 on 2024-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_tickets_ticket_seats_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=788158, editable=False),
        ),
    ]
