# Generated by Django 5.1 on 2024-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exceuted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=561254, editable=False),
        ),
    ]
