# Generated by Django 5.1 on 2024-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_transaction_otp_alter_user_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=393670, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='tickets',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
