# Generated by Django 5.1.3 on 2024-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_food_food_id_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='food_order_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=765240, editable=False),
        ),
    ]
