# Generated by Django 5.1.3 on 2024-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_ticket_food_order_confirmed_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='food_orders',
            field=models.JSONField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=309334, editable=False),
        ),
    ]
