# Generated by Django 5.1.3 on 2024-11-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_transaction_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='exceuted',
            new_name='executed',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=357133, editable=False),
        ),
    ]
