# Generated by Django 5.1.3 on 2024-11-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_theatreadmin_user_alter_transaction_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatreadmin',
            name='theatre',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=125087, editable=False),
        ),
        migrations.AddField(
            model_name='theatreadmin',
            name='theatre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.theatre'),
        ),
    ]
