# Generated by Django 5.1.3 on 2024-11-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_theatreadmin_theatre_alter_transaction_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=863083, editable=False),
        ),
    ]
