# Generated by Django 5.1.3 on 2024-11-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_theatre_shows_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='screen',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=435045, editable=False),
        ),
    ]
