# Generated by Django 5.1.3 on 2024-11-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=632444, editable=False),
        ),
    ]
