# Generated by Django 5.1 on 2024-11-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_movie_genre_alter_transaction_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tickets',
            new_name='seats',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=602733, editable=False),
        ),
    ]
