# Generated by Django 5.1 on 2024-11-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_ticket_price_alter_transaction_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=100)),
                ('user_id', models.UUIDField(default=None, null=True)),
                ('transaction_history', models.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_history',
        ),
        migrations.AddField(
            model_name='show',
            name='available_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=445989, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.wallet'),
        ),
    ]
