# Generated by Django 5.1 on 2024-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_theatre_theatre_admin_theatreadmin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=393682, editable=False),
        ),
    ]
