# Generated by Django 5.1 on 2024-11-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=160798, editable=False),
        ),
    ]
