# Generated by Django 5.1 on 2024-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_user_creation_date_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=799304, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='tickets',
            field=models.JSONField(default='', null=True),
        ),
    ]
