# Generated by Django 5.1 on 2024-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_transaction_otp_alter_user_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('cancelled', 'cancelled'), ('used', 'used')], default='booked', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=372544, editable=False),
        ),
    ]
