# Generated by Django 5.1.3 on 2024-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=342860, editable=False),
        ),
    ]
