# Generated by Django 5.1.3 on 2024-11-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_ticket_food_orders_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=906113, editable=False),
        ),
    ]
