# Generated by Django 5.1.3 on 2024-11-13 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_exceuted_transaction_executed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatreadmin',
            options={'permissions': (('theateradmin', 'User is a theater admin'),)},
        ),
        migrations.RemoveField(
            model_name='theatreadmin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='theatreadmin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='theatreadmin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='theatreadmin',
            name='username',
        ),
        migrations.AddField(
            model_name='theatreadmin',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='theatreadmin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theatreadmin',
            name='theatre',
            field=models.ManyToManyField(related_name='theatre_admin', to='main.theatre'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=568461, editable=False),
        ),
    ]
