# Generated by Django 5.1.3 on 2024-11-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_theatreadmin_options_remove_theatreadmin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='th_admin_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theatreadmin',
            name='theatre',
            field=models.ManyToManyField(null=True, related_name='theatre_admin', to='main.theatre'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=144518, editable=False),
        ),
    ]
