# Generated by Django 5.1.3 on 2024-11-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_wallet_th_admin_wallet_alter_theatreadmin_theatre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatreadmin',
            name='wallet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=272236, editable=False),
        ),
    ]
