# Generated by Django 5.1.3 on 2024-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_theatreadmin_wallet_alter_transaction_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='admin_uuid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=875200, editable=False),
        ),
    ]
