# Generated by Django 5.1.3 on 2024-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_theatre_admin_uuid_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatreadmin',
            name='theatre',
            field=models.ManyToManyField(related_name='theatre_admin', to='main.theatre'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=431721, editable=False),
        ),
    ]
