# Generated by Django 5.1.3 on 2024-11-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='shows',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=332163, editable=False),
        ),
    ]
