# Generated by Django 5.1.3 on 2024-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_food_category_alter_transaction_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=967830, editable=False),
        ),
    ]
