# Generated by Django 5.1.3 on 2024-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_user_google_account_alter_transaction_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='seats',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=158169, editable=False),
        ),
    ]
