from django.urls import path
from .views import *
app_name = "th_admin"
urlpatterns = [
    path("", AdminLoginView.as_view(), name="th_admin"),
    path("home", admin_home, name="home"),
    path("logout", admin_logout, name="logout"),
    path("food", AdminFoodView.as_view(), name="food"),
    path("food/edit/<uuid:food_id>",
         EditFoodView.as_view(), name="edit_food"),
    path("food/add/",
         AddFoodView.as_view(), name="add_food"),
    path("food/delete/<uuid:food_id>",
         delete_food_item, name="delete_food"),
    path("show", AdminShowView.as_view(), name="show"),
    path("show/edit/<uuid:show_id>",
         EditShowView.as_view(), name="edit_show"),
    path("show/add/",
         AddShowView.as_view(), name="add_show"),
    path("show/delete/<uuid:show_id>",
         delete_show_view, name="delete_show"),
    path("bookings", admin_booking_view, name="bookings"),
    path("register", register_th_admin, name="register"),
    path("screens", screen_view, name="screen"),
    path("screen/add", AddScreenView.as_view(),
         name="add_screen"),
    path("screen/edit/<uuid:screen_id>",
         EditScreenView.as_view(), name="edit_screen"),
    path("screen/delete/<uuid:screen_id>",
         delete_screen_view, name="delete_screen"),
    path("ticket_details/<uuid:ticket_id>", admin_ticket_details,
         name="ticket_details"),
    path("tickets/cancel", admin_ticket_cancel,
         name="cancel_ticket"),
    path("tickets/used", admin_ticket_used, name="ticket_used"),
    path('wallet', admin_wallet_view, name="wallet"),
    path("transactions", transactions, name="transactions"),
    path('transaction/<uuid:transaction_id>', transaction, name="transaction"),
    path('theatre', TheatreView.as_view(), name="theatre"),
]
